# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 478)
        MainWindow.setStyleSheet("background: rgb(255, 251, 114)rgb(160, 176, 137)rgb(190, 182, 142)rgb(189, 200, 151)rgb(112, 125, 90);\n"
"color: rgb(255, 255, 191);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.title_edit.setGeometry(QtCore.QRect(240, 20, 321, 20))
        self.title_edit.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.title_edit.setObjectName("title_edit")
        self.text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit.setGeometry(QtCore.QRect(240, 50, 321, 381))
        self.text_edit.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.text_edit.setObjectName("text_edit")
        self.noet_list = QtWidgets.QListWidget(self.centralwidget)
        self.noet_list.setGeometry(QtCore.QRect(10, 40, 211, 111))
        self.noet_list.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.noet_list.setObjectName("noet_list")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(10, 190, 101, 23))
        self.create_btn.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.create_btn.setObjectName("create_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(120, 190, 101, 23))
        self.delete_btn.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.delete_btn.setObjectName("delete_btn")
        self.noet_lnst = QtWidgets.QListWidget(self.centralwidget)
        self.noet_lnst.setGeometry(QtCore.QRect(10, 240, 211, 91))
        self.noet_lnst.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.noet_lnst.setObjectName("noet_lnst")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(50, 160, 141, 23))
        self.save_btn.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.save_btn.setObjectName("save_btn")
        self.add_teg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_teg_btn.setGeometry(QtCore.QRect(10, 400, 131, 23))
        self.add_teg_btn.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.add_teg_btn.setObjectName("add_teg_btn")
        self.unpin_teg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.unpin_teg_btn.setGeometry(QtCore.QRect(10, 370, 131, 23))
        self.unpin_teg_btn.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.unpin_teg_btn.setObjectName("unpin_teg_btn")
        self.search_l = QtWidgets.QLineEdit(self.centralwidget)
        self.search_l.setGeometry(QtCore.QRect(10, 340, 131, 20))
        self.search_l.setObjectName("search_l")
        self.search_teg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_teg_btn.setGeometry(QtCore.QRect(150, 340, 75, 23))
        self.search_teg_btn.setStyleSheet("border-radius: 7px;\n"
"background: rgb(191, 204, 130);\n"
"color: black;")
        self.search_teg_btn.setObjectName("search_teg_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 220, 71, 16))
        self.label.setStyleSheet("\n"
"color: black;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 81, 16))
        self.label_2.setStyleSheet("\n"
"\n"
"color: black;")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "easy Editor"))
        self.create_btn.setText(_translate("MainWindow", "створити замітку"))
        self.delete_btn.setText(_translate("MainWindow", "видалити замітку"))
        self.save_btn.setText(_translate("MainWindow", "зберегти замітку"))
        self.add_teg_btn.setText(_translate("MainWindow", "додати до замітки"))
        self.unpin_teg_btn.setText(_translate("MainWindow", "відкріпити від замітки"))
        self.search_teg_btn.setText(_translate("MainWindow", "шукати тег"))
        self.label.setText(_translate("MainWindow", "Список тегів"))
        self.label_2.setText(_translate("MainWindow", "Список заміток"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
